// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Age      *int    `json:"age"`
	Gender   *bool   `json:"gender"`
	Phone    *string `json:"phone"`
	Address  *string `json:"address"`
}

type UpdateUser struct {
	ID       int     `json:"id"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Age      *int    `json:"age"`
	Gender   *bool   `json:"gender"`
	Phone    *string `json:"phone"`
	Address  *string `json:"address"`
}

type UserConnection struct {
	Total int     `json:"total"`
	Nodes []*User `json:"nodes"`
}

type UserFilter struct {
	Limit   int     `json:"limit"`
	Offset  int     `json:"offset"`
	Search  *string `json:"search"`
	Order   *string `json:"order"`
	OrderBy *string `json:"orderBy"`
	Gender  *bool   `json:"gender"`
}
